### ISSUE TITLE
Update dependency pagerfanta/pagerfanta

### ISSUE THREAD

**Issue by mussbach** [demos-europe/edt#112]
pagerfanta/pagerfanta is currently used at version `^2.7`, current version is [4.2.0](https://github.com/BabDev/Pagerfanta/releases/tag/v4.2.0). Would it be possible to update this dependency? Perhaps you may increase the majors one by one

**Comment by dresslerdemos** [comment]
`pagerfanta/pagerfanta` is no longer a dependency.
Instead, `pagerfanta/core` became a depenency, but is supported in version 4.2.0.
