### ISSUE TITLE
Allow aggregated/generated backing Type classes

### ISSUE THREAD

**Issue by dresslerdemos** [demos-europe/edt#73]
Currently the `EntityBasedInterface::getEntityClass` can be used to define the Doctrine entity class that backs a (resource) type and is supposed to be used when building DQL queries via `QueryBuilderPreparer`. This however does not allow to define a Type that is not backed by a specific Doctrine entity but aggregated from the relational data instead.

* maybe this should not be a feature of EDT, as it seems to be covered by [entities backed by view tables](https://stackoverflow.com/questions/8377671)
* necessary refactoring should count in https://github.com/demos-europe/edt/issues/40 as well

**Comment by dresslerdemos** [comment]
Current state: On the resource type level the current library implementation simply requires instances of an entity class, whose data (properties) that can be accessed via the chosen `PropertyAccessorInterface` implementation. How this entity is build/retrieved is completely up to the implementation of the `RepositoryInterface` corresponding to that entity.

Thus, persueing this issue basically means providing default behavior to be used in `RepositoryInterface` implementations by providing tooling or classes inheriting from `RepositoryInterface`.

**Comment by joorei** [comment]
At this point, this library provides multiple points on different abstraction levels to aggregate data into a single resource:
* [the upmost interfaces, handling requests](https://github.com/demos-europe/edt/blob/main/docs/concepts.adoc#request-kinds), where complete freedom is given how the entity is put together and what (CRUD) aspects to support
* implementing a custom `RepositoryInterface`, as mentioned [above](https://github.com/demos-europe/edt/issues/73#issuecomment-2059077187), requiring the implementation of CRUD capabilities, but still being indifferent regarding the implementation of those capabilities
* implementing a custom [OffsetEntityProviderInterface](https://github.com/demos-europe/edt/blob/591cb847ffe7b23fd951e02de9267c3ef13d4daf/packages/queries/src/Contracts/OffsetEntityProviderInterface.php), which integrates well into the existing architecture (and allows to re-use most logic), but will cover the reading of the entity only.

The original issue can therefore be considered resolved.

However, for none of those approaches it is clear how to provide generic utilities to ease the aggregation of data into a single resource (or dividing it again when updated) without getting too specific (i.e. not usable for most cases) or too simple (i.e. no actual value).

If clear requirements for such utility emerges, a new issue can be created focusing on this task.
